services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: mark_project_postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"